### ISSUE TITLE
android 6.0动态修复  枚举出错

### ISSUE THREAD

**Issue by Dongzzzz** [dodola/RocooFix#32]
version1 代码：
```java
public class DemoActivity7 extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test_7);


    }

    public void load(View view) {
        RocooFix.initPathFromAssetsRuntime(this, "patch.jar");
    }

    public void start(View view) {
        startActivity(new Intent(this, DemoActivity8.class));
    }
}
```
```java
public class DemoActivity8 extends Activity {

    private TextView textView;


    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test_8);
        textView = (TextView) findViewById(R.id.text);
        textView.setText("456");

    }
}
```

version2 代码:

Demo7 不变

Demo8:
```java
public class DemoActivity8 extends Activity {

    private TextView textView;
    //
    private TestInterface impl;
    int count = 0;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test_8);
        textView = (TextView) findViewById(R.id.text);
        textView.setText("456");

        impl = new TestInterfaceImpl();

        textView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (count % 3 == 0) {
                    impl.test(Test.ONLINE);
                } else if (count % 3 == 1) {
                    impl.test(Test.TEST);
                } else {
                    impl.test(Test.PRE);
                }
                count++;
            }
        });
    }


    public static class TestInterfaceImpl implements TestInterface {
        @Override
        public void test(Test test) {


            switch (test) {
                case ONLINE:
                    System.out.println("test = [" + test + "online" + "]");
                    break;
                case TEST:
                    System.out.println("test = [" + test + "TEST" + "]");
                    break;
                case PRE:
                    System.out.println("test = [" + test + "PRE" + "]");
                    break;
            }
        }
    }
}
```
新增枚举 Test 接口TestInterface
```java 
public enum Test {

    ONLINE, TEST, PRE;

}
```
```java 
public interface TestInterface {
    void test(Test test);
}
```
version 3:
```java 
public enum Test {

    ONLINE, TEST, PRE , NEW_ADD;

}
```
新增了NEW_ADD ， Demo8里面也新增了对NEW_ADD的处理。

把version2 与version1 差异生成的patch.jar 重命名为dex.jar。 把这个当成动态加载的一个模块
```java 
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        RocooFix.init(this);
        RocooFix.initPathFromAssets(this,"dex.jar");
    }
```
version3 与 version2 差异生成的patch.jar来当成动态修复的jar

Application中执行动态加载dex.jar，其中dex.jar包含一个枚举类 Test

Demo7中点击进行动态修复，在Test中新增一个NEW_ADD。
然后进入Demo8，点击TextView。就会出错.

报错信息如下

```
06-08 11:10:40.462 13187-13187/cn.eclicks.chelun D/#######: Malloc memory, size : 40
06-08 11:10:40.463 13187-13187/cn.eclicks.chelun D/#######: Read Memory to 0xffffffffae2b3890
06-08 11:10:40.463 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae289000
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae28900c
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38b4
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38ac
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3890
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3894
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3898
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38a0
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38a4
06-08 11:10:40.465 13187-13187/cn.eclicks.chelun D/#######: Malloc memory, size : 144
06-08 11:10:40.466 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae288000
06-08 11:10:40.466 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38b0
06-08 11:10:40.469 13187-13187/cn.eclicks.chelun D/#######: Malloc memory, size : 40
06-08 11:10:40.469 13187-13187/cn.eclicks.chelun D/#######: Read Memory to 0xffffffffae2b38b8
06-08 11:10:40.469 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae080000
06-08 11:10:40.471 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae08000c
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38dc
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38d4
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38b8
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38bc
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38c0
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38c8
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38cc
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Malloc memory, size : 144
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae07f000
06-08 11:10:40.472 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b38d8
                                                            
                                                            [ 06-08 11:10:40.474  4221: 4748 D/         ]
                                                            file:device/hisi/common/liblights/lights.c, func:set_light_backlight, brightness=16
06-08 11:10:40.476 13187-13187/cn.eclicks.chelun D/#######: Malloc memory, size : 40
06-08 11:10:40.477 13187-13187/cn.eclicks.chelun D/#######: Read Memory to 0xffffffffae2b3930
06-08 11:10:40.477 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffadcab000
06-08 11:10:40.478 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffadcab00c
06-08 11:10:40.478 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3954
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b394c
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3930
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3934
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3938
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3940
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3944
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Malloc memory, size : 144
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffacd96000
06-08 11:10:40.479 13187-13187/cn.eclicks.chelun D/#######: Write Memory to 0xffffffffae2b3950

06-08 11:10:54.844 13187-13187/cn.eclicks.chelun D/AndroidRuntime: Shutting down VM
06-08 11:10:54.846 13187-13187/cn.eclicks.chelun E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: cn.eclicks.chelun, PID: 13187
                                                                   java.lang.ExceptionInInitializerError
                                                                       at cn.eclicks.chelun.enums.Test.values(Test.java:9)
                                                                       at cn.eclicks.chelun.DemoActivity8$2.<clinit>(DemoActivity8.java:55)
                                                                       at cn.eclicks.chelun.DemoActivity8$TestInterfaceImpl.test(DemoActivity8.java:55)
                                                                       at cn.eclicks.chelun.DemoActivity8$1.onClick(DemoActivity8.java:38)
                                                                       at android.view.View.performClick(View.java:5264)
                                                                       at android.view.View$PerformClick.run(View.java:21297)
                                                                       at android.os.Handler.handleCallback(Handler.java:743)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:150)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                    Caused by: java.lang.ArrayStoreException: cn.eclicks.chelun.enums.Test cannot be stored in an array of type cn.eclicks.chelun.enums.Test[]
                                                                       at cn.eclicks.chelun.enums.Test.<clinit>(Test.java:9)
                                                                       at cn.eclicks.chelun.enums.Test.values(Test.java:9) 
                                                                       at cn.eclicks.chelun.DemoActivity8$2.<clinit>(DemoActivity8.java:55) 
                                                                       at cn.eclicks.chelun.DemoActivity8$TestInterfaceImpl.test(DemoActivity8.java:55) 
                                                                       at cn.eclicks.chelun.DemoActivity8$1.onClick(DemoActivity8.java:38) 
                                                                       at android.view.View.performClick(View.java:5264) 
                                                                       at android.view.View$PerformClick.run(View.java:21297) 
                                                                       at android.os.Handler.handleCallback(Handler.java:743) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:150) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
```

把静态修复看成是 模块化的动态加载dex。 动态修复是修复模块dex的错误。
这样是不是可以理解为 若果模块dex里面有枚举 ，动态修复进行替换的时候 就会报错。

**Comment by dodola** [comment]
@Dongzzzz 由于两种方式的class加载机制不同，所以这两种方式混用会造成classloader之间的冲突，你提出的这种补丁情况我用方式1是正常的，方式2主要是更改方法的entrypoints，并不会替换掉已经加载的class的所有内容，比如新增方法这种情况就不适用方式2，所以按照实际情况选择使用
