### ISSUE TITLE
作者大人：我在联想一款手机上运行android4.4.4  运行静态加载报错Class ref in  pre-verified class resoved to unexpected  implementation

### ISSUE THREAD

**Issue by 710224800** [dodola/RocooFix#38]
作者大人：我在联想一款手机上运行android4.4.4  运行静态加载报错Class ref in  pre-verified class resoved to unexpected  implementation

**Comment by yangqianghui** [comment]
有没有其他错误信息  大家看看

**Comment by yangqianghui** [comment]
导出jar时不能带接口文件，否则会报以下错：
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

**Comment by dodola** [comment]
@710224800 卧槽，我还真没想到这个情况，我试试=_=，看来我得用另一种方法来处理这种情况了

**Comment by qq14528648** [comment]
海马模拟器也出这个问题了。
下面的LOG：
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                          at com.dodola.rocoosample.MainActivity$1.onClick(MainActivity.java:23)
                                                                          at android.view.View.performClick(View.java:4204)
                                                                          at android.view.View$PerformClick.run(View.java:17355)
                                                                          at android.os.Handler.handleCallback(Handler.java:725)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5069)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by wangjunhe** [comment]
4.4 问题严重 我好像没有涉及接口文件也会报这个错

**Comment by DylanMay** [comment]
红米1s 也是4.4.4版本，也会出现同样的错误

**Comment by DylanMay** [comment]
if (!fromUnverifiedConstant &&
    IS_CLASS_FLAG_SET(referrer, CLASS_ISPREVERIFIED))
{
    ClassObject* resClassCheck = resClass;
    if (dvmIsArrayClass(resClassCheck))
        resClassCheck = resClassCheck->elementClass;

    if (referrer->pDvmDex != resClassCheck->pDvmDex &&
        resClassCheck->classLoader != NULL)
    {
        ALOGW("Class resolved by unexpected DEX:"
             " %s(%p):%p ref [%s] %s(%p):%p",
            referrer->descriptor, referrer->classLoader,
            referrer->pDvmDex,
            resClass->descriptor, resClassCheck->descriptor,
            resClassCheck->classLoader, resClassCheck->pDvmDex);
        ALOGW("(%s had used a different %s during pre-verification)",
            referrer->descriptor, resClass->descriptor);
        dvmThrowIllegalAccessError(
            "Class ref in pre-verified class resolved to unexpected "
            "implementation");
        return NULL;
    }
}


看这篇文章说好像解决了这个问题

**Comment by Dongzzzz** [comment]
@dodola 好多4.4.4的手机上都会出现这个问题。很奇怪。

**Comment by DylanMay** [comment]
有一点不理解的是，当前这个方案也是基于Qzone的，已经解决了这个验证不通过的问题，为什么还会出现呢

**Comment by Dongzzzz** [comment]
你是不是在Application中引用到了A类， 然后A类除了问题。把A类打入到了patch.jar中。然后静态修复出问题了？
