### ISSUE TITLE
运行静态加载demo报错com.dodola.rocoosample.runtimefix E/Rocoo: replaceMethod 

### ISSUE THREAD

**Issue by 710224800** [dodola/RocooFix#42]
06-14 10:04:18.951 22434-22434/com.dodola.rocoosample.runtimefix E/Rocoo: replaceMethod
                                                                          java.lang.IllegalStateException: Cannot create backup method from :: public java.lang.String com.dodola.rocoosample.HelloHack.showHello()
                                                                              at com.lody.legend.art.ArtMethod.backup(ArtMethod.java:133)
                                                                              at com.lody.legend.HookManager.hookMethodArt(HookManager.java:197)
                                                                              at com.lody.legend.HookManager.hookMethod(HookManager.java:135)
                                                                              at com.dodola.rocoofix.RocooFix.replaceMethod(RocooFix.java:626)
                                                                              at com.dodola.rocoofix.RocooFix.fixClass(RocooFix.java:589)
                                                                              at com.dodola.rocoofix.RocooFix.applyPatchRuntime(RocooFix.java:565)
                                                                              at com.dodola.rocoofix.RocooFix.initPathFromAssetsRuntime(RocooFix.java:513)
                                                                              at com.dodola.rocoosample.runtimefix.MainActivity$1.onClick(MainActivity.java:24)
                                                                              at android.view.View.performClick(View.java:5199)
                                                                              at android.view.View$PerformClick.run(View.java:21155)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5415)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by 710224800** [comment]
手机是nexus 5
