### ISSUE TITLE
java.lang.NoClassDefFoundError 如何处理？

### ISSUE THREAD

**Issue by gzejia** [dodola/RocooFix#5]
05-27 18:40:29.911 32446-32446/com.dodola.rocoosample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.dodola.rocoosample, PID: 32446
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dodola/rocoo/Hack;
                                                                            at com.dodola.rocoosample.MainActivity.<init>(Unknown Source)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at java.lang.Class.newInstance(Class.java:1650)
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                                                            at android.os.Handler.dispatchMessage(Handler.java)
                                                                            at android.os.Looper.loop(Looper.java)
                                                                            at android.app.ActivityThread.main(ActivityThread.java)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dodola.rocoo.Hack" on path: DexPathList[[zip file "/data/app/com.dodola.rocoosample-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                            at com.dodola.rocoosample.MainActivity.<init>(Unknown Source) 
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at java.lang.Class.newInstance(Class.java:1650) 
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java) 
                                                                            at android.os.Looper.loop(Looper.java) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                        	Suppressed: java.lang.ClassNotFoundException: com.dodola.rocoo.Hack
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                            		... 16 more
                                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by gzejia** [comment]
我是今天才将项目down下来的，在配置里加上includePackageNames = ['com.dodola.rocoo']虽然避开错误了，但是并没有补丁生成。

**Comment by dodola** [comment]
@gzejia 灰常抱歉，我的.gitignore把*.dex文件给过滤掉了，所以没有上传上去😂,现在好了
