### ISSUE TITLE
测试动态修复时候crash，麻烦看看

### ISSUE THREAD

**Issue by WilliamTata** [dodola/RocooFix#6]
05-28 19:19:31.299 20849-20849/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.ExceptionInInitializerError
                                                       at com.lody.legend.b.a.<init>(Unknown Source)
                                                       at com.lody.legend.b.a.a(Unknown Source)
                                                       at com.lody.legend.a.b(Unknown Source)
                                                       at com.lody.legend.a.a(Unknown Source)
                                                       at com.a.a.a.a(Unknown Source)
                                                       at com.a.a.a.d(Unknown Source)
                                                       at com.a.a.a.c(Unknown Source)
                                                       at com.hotfix.hotfixdemo.b.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:4223)
                                                       at android.view.View$PerformClick.run(View.java:17275)
                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.UnsatisfiedLinkError: unknown failure
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:370)
                                                       at java.lang.System.loadLibrary(System.java:535)
                                                       at com.lody.legend.utility.LegendNative.<clinit>(Unknown Source)
                                                       at com.lody.legend.b.a.<init>(Unknown Source) 
                                                       at com.lody.legend.b.a.a(Unknown Source) 
                                                       at com.lody.legend.a.b(Unknown Source) 
                                                       at com.lody.legend.a.a(Unknown Source) 
                                                       at com.a.a.a.a(Unknown Source) 
                                                       at com.a.a.a.d(Unknown Source) 
                                                       at com.a.a.a.c(Unknown Source) 
                                                       at com.hotfix.hotfixdemo.b.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:4223) 
                                                       at android.view.View$PerformClick.run(View.java:17275) 
                                                       at android.os.Handler.handleCallback(Handler.java:615) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:4898) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by WilliamTata** [comment]
@dodola 麻烦给看看

**Comment by dodola** [comment]
@WilliamTata 请提供一下测试机型和Android版本号

**Comment by WilliamTata** [comment]
@dodola 测试机型是note2 ，Android版本号：4.1.2

**Comment by WilliamTata** [comment]
@dodola 并且我测试发现，对于枚举类也会出现错误

**Comment by Dongzzzz** [comment]
-keep class com.dodola.rocoofix.** {*;}
-keep class com.lody.legend.** {*;}

试试看 是不是混淆的问题？ legend下的是不能被混淆的  特别是 LegendNative 这个里面有native方法

**Comment by dodola** [comment]
@WilliamTata  -keep class com.lody.legend.* {*;} 这个是不能混淆的，我已经补充进了文档里
