### ISSUE TITLE
加入工程后，编译提示错误 java.lang.NoClassDefFoundError: com/dodola/rocoo/Hack，删除后依旧

### ISSUE THREAD

**Issue by c1024** [dodola/RocooFix#70]
我把RocooFix引入自己的工程编译提示如下错误:

Error:Execution failed for task ':whiteCollar:compileProdPreviewJavaWithJavac'.
> java.lang.NoClassDefFoundError: com/dodola/rocoo/Hack。

还有项目中有用到android-apt生成代码。结果代码没有生成。
删除RocooFix，问题依旧。
目前无法编译打包。请问这是出了什么问题，在线急等。

**Comment by c1024** [comment]
用./gradlew clean installProdDebug --stacktrace --info编译得到如下异常信息：
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ': whiteCollar:compileProdPreviewJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/dodola/rocoo/Hack
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
        at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: com/dodola/rocoo/Hack
        at dagger.Provides$Type.<init>(Provides.java:50)
        at dagger.Provides$Type.<clinit>(Provides.java:55)
        at com.sun.tools.javac.model.AnnotationProxyMaker$ValueVisitor.visitEnum(AnnotationProxyMaker.java:226)
        at com.sun.tools.javac.code.Attribute$Enum.accept(Attribute.java:349)
        at com.sun.tools.javac.model.AnnotationProxyMaker$ValueVisitor.getValue(AnnotationProxyMaker.java:166)
        at com.sun.tools.javac.model.AnnotationProxyMaker.generateValue(AnnotationProxyMaker.java:144)
        at com.sun.tools.javac.model.AnnotationProxyMaker.getAllReflectedValues(AnnotationProxyMaker.java:102)
        at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:88)
        at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:79)
        at com.sun.tools.javac.code.AnnoConstruct.getAnnotation(AnnoConstruct.java:179)
        at dagger.internal.codegen.ContributionType.fromBindingMethod(ContributionType.java:110)
        at dagger.internal.codegen.ProvidesMethodValidator.validate(ProvidesMethodValidator.java:118)
        at dagger.internal.codegen.ModuleProcessingStep.validateProvidesMethods(ModuleProcessingStep.java:171)
        at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:81)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 34 more
Caused by: java.lang.ClassNotFoundException: com.dodola.rocoo.Hack
        ... 58 more

**Comment by dodola** [comment]
@c1024  擦，这个东东和dragger的build有冲突

**Comment by shoyu666** [comment]
@c1024   请问是不是执行了自动化测试

**Comment by c1024** [comment]
没有自动化测试

**Comment by c1024** [comment]
最奇怪的是，移除RocooFix,编译还是会同样错误

**Comment by shoyu666** [comment]
@c1024    那whiteCollar:compileProdPreviewJavaWithJavac执行的是什么
build目录删除了，另外一处RocooFix插件，再编译

**Comment by c1024** [comment]
whiteCollar:compileProdPreviewJavaWithJavac是./gradlew clean installProdDebug编译过程中的一步。
build目录删除没用。我项目代码clone到其他目录，编译也是同样问题。目前自己电脑那个项目编译一直提示那个异常，其他电脑clone代码就没问题。。。

**Comment by c1024** [comment]
目前最根本问题是我没有引用Hack类。还是一直提示异常java.lang.NoClassDefFoundError: com/dodola/rocoo/Hack

**Comment by shoyu666** [comment]
@c1024   建议加入561394234群交流看看

**Comment by c1024** [comment]
把用户目录.gradle目录里面内容删除掉，同步半天，编译正常了

**Comment by dodola** [comment]
@c1024 已经修复了，造成问题表示抱歉
