### ISSUE TITLE
Execution failed for task ':app:rocooJarBeforeDexDebug'.

### ISSUE THREAD

**Issue by apkhook** [dodola/RocooFix#76]
17:34:56.190 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:34:56.191 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:rocooJarBeforeDexDebug'.
17:34:56.191 [ERROR] [org.gradle.BuildExceptionReporter] > **com/android/dx/cf/direct/AttributeFactory**

堆栈信息：
17:34:56.210 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: com/android/dx/cf/direct/AttributeFactory
17:34:56.210 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dodola.rocoofix.utils.NuwaProcessor.class$(NuwaProcessor.groovy)
17:34:56.210 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dodola.rocoofix.utils.NuwaProcessor.$get$$class$com$dodola$rocoofix$ref$Path(NuwaProcessor.groovy)
17:34:56.211 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dodola.rocoofix.utils.NuwaProcessor.processJar(NuwaProcessor.groovy:30)
17:34:56.211 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dodola.rocoofix.utils.NuwaProcessor$processJar.call(Unknown Source)
17:34:56.211 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dodola.rocoofix.RocooFixPlugin$_applyTask_closure1$_closure3$_closure9$_closure12.doCall(RocooFixPlugin.groovy:194)
17:34:56.211 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dodola.rocoofix.RocooFixPlugin$_applyTask_closure1$_closure3$_closure9.doCall(RocooFixPlugin.groovy:190)

**Comment by apkhook** [comment]
当开启了multiDex插件会出现该问题

**Comment by shoyu666** [comment]
@apkhook   
试下com.android.tools.build:gradle:2.1.2

**Comment by zsunkun** [comment]
使用 2.1.2仍然会报这个错
