### ISSUE TITLE
项目中包含枚举类，运行项目时候出现crash，麻烦给看看

### ISSUE THREAD

**Issue by WilliamTata** [dodola/RocooFix#8]
05-30 11:29:30.565 30290-30290/? E/dalvikvm: Could not find class 'com.dodola.rocoo.Hack', referenced from method com.hotfix.hotfixdemo.c.<init>
05-30 11:29:30.570 30290-30290/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.ExceptionInInitializerError
                                                       at com.hotfix.hotfixdemo.MyApplication.<init>(Unknown Source)
                                                       at java.lang.Class.newInstanceImpl(Native Method)
                                                       at java.lang.Class.newInstance(Class.java:1319)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:997)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4201)
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:140)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NoClassDefFoundError: com.dodola.rocoo.Hack
                                                       at com.hotfix.hotfixdemo.c.<init>(Unknown Source)
                                                       at com.hotfix.hotfixdemo.c.<clinit>(Unknown Source)
                                                       at com.hotfix.hotfixdemo.MyApplication.<init>(Unknown Source) 
                                                       at java.lang.Class.newInstanceImpl(Native Method) 
                                                       at java.lang.Class.newInstance(Class.java:1319) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:496) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4201) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:140) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:4898) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by WilliamTata** [comment]
@dodola 项目中包含枚举类的时候，运行的时候，会crash，麻烦给看看

**Comment by dodola** [comment]
@WilliamTata 你获取一下最新的代码运行看看还有没有这个问题
