### ISSUE TITLE
动态修复出错

### ISSUE THREAD

**Issue by xuyangbill** [dodola/RocooFix#85]
08-05 18:30:50.714 18022-19110/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[MessageHandleThread]
                                                   Process: ***, PID: 18022
                                                   java.lang.UnsatisfiedLinkError: Couldn't load legend from loader dalvik.system.PathClassLoader[DexPathList[[dex file "dalvik.system.DexFile@4247c8c0", zip file "/data/app/***.apk", zip file "/data/data/***/code_cache/secondary-dexes/***-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/***-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                       at java.lang.System.loadLibrary(System.java:526)
                                                       at com.lody.legend.utility.LegendNative.<clinit>(LegendNative.java:17)
                                                       at com.lody.legend.dalvik.DalvikMethodStruct.<init>(DalvikMethodStruct.java:63)
                                                       at com.lody.legend.dalvik.DalvikMethodStruct.of(DalvikMethodStruct.java:73)
                                                       at com.lody.legend.HookManager.hookMethodDalvik(HookManager.java:157)
                                                       at com.lody.legend.HookManager.hookMethod(HookManager.java:137)
                                                       at com.dodola.rocoofix.RocooFix.replaceMethod(RocooFix.java:665)
                                                       at com.dodola.rocoofix.RocooFix.fixClass(RocooFix.java:628)
                                                       at com.dodola.rocoofix.RocooFix.applyPatchRuntime(RocooFix.java:604)
                                                       at ***.receiver.MessageReceiver.onReceivePassThroughMessage(MessageReceiver.java:30)
                                                       at com.xiaomi.mipush.sdk.MessageHandleService.onHandleIntent(Unknown Source)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by xuyangbill** [comment]
红米note1 4.4.4 miui 8 6.7.28
scanref = true
