### ISSUE TITLE
动态修复出错

### ISSUE THREAD

**Issue by xuyangbill** [dodola/RocooFix#86]
08-05 20:48:00.400 14905-15347/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[MessageHandleThread]
                                                   Process: ***, PID: 14905
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/***/files/hotfix/rocoo.dex", zip file "/data/app/***-1/base.apk"],nativeLibraryDirectories=[/data/app/***-1/lib/arm, /data/app/***-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "liblegend.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at com.lody.legend.utility.LegendNative.<clinit>(LegendNative.java:17)
                                                       at com.lody.legend.art.ArtMethod.<init>(ArtMethod.java:42)
                                                       at com.lody.legend.art.ArtMethodStructV23.<init>(ArtMethodStructV23.java:76)
                                                       at com.lody.legend.art.ArtMethod.of(ArtMethod.java:49)
                                                       at com.lody.legend.HookManager.hookMethodArt(HookManager.java:195)
                                                       at com.lody.legend.HookManager.hookMethod(HookManager.java:135)
                                                       at com.dodola.rocoofix.RocooFix.replaceMethod(RocooFix.java:665)
                                                       at com.dodola.rocoofix.RocooFix.fixClass(RocooFix.java:628)
                                                       at com.dodola.rocoofix.RocooFix.applyPatchRuntime(RocooFix.java:604)
                                                       at ***.receiver.MessageReceiver.onReceivePassThroughMessage(MessageReceiver.java:28)
                                                       at com.xiaomi.mipush.sdk.MessageHandleService.onHandleIntent(Unknown Source)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by xuyangbill** [comment]
n5 6.0.1
scanref = true
