### ISSUE TITLE
6.0以上报错，但是补丁能生效 Unable to open zip file: /data/user/0/cn.shoppingm.god.qa/files/hotfix/rocoo.dex

### ISSUE THREAD

**Issue by towinner** [dodola/RocooFix#96]
Unable to open zip file: /data/user/0/cn.shoppingm.god.qa/files/hotfix/rocoo.dex
08-22 14:39:46.218 1245-1245/cn.shoppingm.god.qa:locationpush E/System: java.util.zip.ZipException: Not a zip archive
                                                                            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:397)
                                                                            at java.util.zip.ZipFile.<init>(ZipFile.java:175)
                                                                            at java.util.zip.ZipFile.<init>(ZipFile.java:131)
                                                                            at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:452)
                                                                            at dalvik.system.DexPathList$Element.findResource(DexPathList.java:499)
                                                                            at dalvik.system.DexPathList.findResource(DexPathList.java:360)
                                                                            at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:67)
                                                                            at java.lang.ClassLoader.getResource(ClassLoader.java:403)
                                                                            at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:442)
                                                                            at java.lang.Class.getResourceAsStream(Class.java:1169)
                                                                            at com.amap.api.mapcore2d.cz.a(Util.java:42)
                                                                            at com.amap.api.mapcore2d.cq.<init>(ZoomControllerView.java:59)
                                                                            at com.amap.api.mapcore2d.b.a(AMapDelegateImpGLSurfaceView.java:1337)
                                                                            at com.amap.api.mapcore2d.b.<init>(AMapDelegateImpGLSurfaceView.java:1283)
                                                                            at com.amap.api.mapcore2d.ba.a(MapFragmentDelegateImp.java:45)
                                                                            at com.amap.api.maps2d.MapView.getMap(MapView.java:108)
                                                                            at cn.shoppingm.god.service.UploadLocationService.a(UploadLocationService.java:89)
                                                                            at cn.shoppingm.god.service.UploadLocationService.onCreate(UploadLocationService.java:73)
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2884)
                                                                            at android.app.ActivityThread.access$1900(ActivityThread.java:153)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by xiaobaoKing1** [comment]
哥们解决没这个问题？ 我的不生效。也报了这个错。 @towinner
